sudo: false
language: node_js
node_js:
  - "0.10"
  - "0.12"
before_install:
  - npm install -g npm@~1.4.28
before_script:
  - npm install -g --unsafe-perm node-red
  - npm install -g istanbul grunt-cli
  - npm install coveralls
  - npm install nock@~0.48.0
